library(dplyr)
library(tidyverse)
library(moments)
library(tseries)
df <- read.csv("C:/Users/Propanone/Desktop/Finance/SP500/GSPC.csv")
df <- df %>% filter(!is.na(Change))
df1 <- read.csv("C:/Users/Propanone/Desktop/Finance/SP500/AAPL.csv")
df1 <- df1 %>% filter(!is.na(Change))
sect <- intersect(df1$Date, df$Date)
df <- df %>% filter(Date %in% sect)
df1 <- df1 %>% filter(Date %in% sect)
dff <- df %>% filter(between(Change, quantile(Change, .25, na.rm = TRUE)-1.5*IQR(Change, na.rm=TRUE), quantile(Change, .75, na.rm = TRUE)+1.5*IQR(Change, na.rm=TRUE)))
df1f <- df1 %>% filter(between(Change, quantile(Change, .25, na.rm = TRUE)-1.5*IQR(Change, na.rm=TRUE), quantile(Change, .75, na.rm = TRUE)+1.5*IQR(Change, na.rm=TRUE)))
sectf <- intersect(df1f$Date, dff$Date)
dff <- dff %>% filter(Date %in% sectf)
df1f <- df1f %>% filter(Date %in% sectf)
df_p <- df %>% summarize(mean(Change), sd(Change), kurtosis(Change), skewness(Change))
df1_p <- df1 %>% summarize(mean(Change), sd(Change), kurtosis(Change), skewness(Change))
dff_p <- dff %>% summarize(mean(Change), sd(Change), kurtosis(Change), skewness(Change))
df1f_p <- df1f %>% summarize(mean(Change), sd(Change), kurtosis(Change), skewness(Change))
r <- data.frame("ratio" = df$Change/df1$Change)
ro <- r %>% filter(between(ratio, quantile(ratio, .25, na.rm = TRUE)-1.5*IQR(ratio, na.rm=TRUE), quantile(ratio, .75, na.rm = TRUE)+1.5*IQR(ratio, na.rm=TRUE)))
rf <- data.frame("ratio" = dff$Change/df1f$Change)
spn <- replicate(2000, prod(1+sample(rnorm(1000, dff_p$`mean(Change)`, dff_p$`sd(Change)`), 90, replace = TRUE)), simplify = FALSE)
spn <- data.frame("prod" = unlist(spn))
sp <- replicate(2000, prod(1+sample(dff$Change, 90, replace = TRUE)), simplify = FALSE)
sp <- data.frame("prod" = unlist(sp))
sp %>% ggplot(aes(prod)) + geom_histogram(binwidth = 0.01)
nrow(sp %>% filter(prod>1))/nrow(sp)
sp %>% ggplot(aes(sample=prod)) + stat_qq() + stat_qq_line()